### ISSUE TITLE
Contradiction on HTML tag

### ISSUE THREAD

**Issue by grv87** [audreyr/favicon-cheat-sheet#76]
> it's best for cross-browser compatibility not to use any HTML

vs

> Explicitness is best, so we both name it favicon.ico and explicitly specify the <link> tag.

So, should `link` tag be added or not?

**Comment by chindraba-work** [comment]
@grv87 Both. 

If the site is using **only** the `favicon.ico`, that falls under "The Basics" and will work anywhere and the `<link>` tag is not needed.

If you want to use something else instead, such as `mysite.ico` or `favicon.png`, or if you place the file somewhere other the site root, then you MUST use a `<link>` tag, and it may, or may not, work in older browsers.

If you are providing multiple options, for multiple devices and uses, then you SHOULD still have the `favicon.ico` in the site root, _and_ include the `<link>` tag for it in the HTML, along with the tags for the other files. Keeping the old default `favicon.ico` in the default place, will allow _any_ browser to find it if/when all else fails. The `<link>` tags help smarter browsers find, and display, what you prefer to show.

**Comment by grv87** [comment]
@chindraba-work, thanks for explanation!
As you worded, I got it.
